name: Terraform CI

on:
  pull_request:
    paths:
      - "**/*.tf"
      - ".github/workflows/terraform-ci.yml"
  push:
    branches: [main]
    paths:
      - "**/*.tf"

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, uat, prod]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: envs/${{ matrix.environment }}
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: envs/${{ matrix.environment }}
        run: terraform validate
